;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-left-brace
        TeX-insert-backslash
        beginning-of-visual-line
        c-electric-paren
        c-electric-star
        c-indent-line-or-region
        coffee-dedent-line-backspace
        end-of-visual-line
        indent-for-tab-command
        kill-region
        kill-visual-line
        latex/beginning-of-line
        org-beginning-of-line
        org-end-of-line
        org-force-self-insert
        org-metaright
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        ))
